### ISSUE TITLE
📚Review and Redesign of Mina's Tokenomics post Hardfork 

### ISSUE THREAD

**Issue by TyrellCorp2020** [MinaFoundation/Core-Grants#28]
https://github.com/MinaFoundation/Core-Grants/issues/31

**Comment by lampardlamps** [comment]
hi @TyrellCorp2020 , what does it mean for the RFCs to be changed from PRs to issues here, is there any work planned for this soon please?

**Comment by kantp** [comment]
We have an RFP for this now, in #31
